// hint for reading the snapshots generated by this file:
// it is important to check that a rule doesn't only enter `meta.embedded.block.graphql`
// but also leaves it again

/* NormalComment */ `query Foo {test}`;

// prettier-ignore
{
const _1 = /* GraphQL */`query Q1 {test}`;
const _2 =
/* GraphQL */`
query Q2 {
  test
}
`;
}

/* GraphQL */ `query Q3 {test}`;
/*GraphQL*/ `query Q4 {test}`;
/** GraphQL */ `query Q5 {test}`;

const _3 = /* GraphQL */ `
  query Q6 {
    test
  }
`;

// syntax highlighting cannot work in all examples after this - textmate grammars don't work over multiple lines like this

/**
 * GraphQL
 */ `query Q7 {test}`;

/* GraphQL */
`query Q8 {test}`;

/* graphql */
`query Q9 {test}`;

/* gql */
`query Q10 {test}`;
