// hint for reading the snapshots generated by this file:
// it is important to check that a rule doesn't only enter `meta.embedded.block.graphql`
// but also leaves it again

`#NormalComment
query Foo {test}`;

`#graphql
query Q1 {test}`;

` # graphql
query Q2 {test}`;

`# GraphQL
query Q3 {
  test
}`;

`#gql
# normal comment
query Q4 {
  test
}`;

`#graphql
query Q5 {
  test
}`;

// syntax highlighting cannot work in all examples after this - textmate grammars don't work over multiple lines like this
`

# graphql

query Q6 {
  test
}
`;
